version: '3.3'
services:
    dp-cantabular-xlsx-exporter:
        build:
            context: ../../../dp-cantabular-xlsx-exporter
            dockerfile: Dockerfile.local
        command:
            - go 
            - test 
            - -cover 
            - -coverpkg=github.com/ONSdigital/dp-cantabular-xlsx-exporter/... 
            - -component
        volumes:
            - ../../:/dp-cantabular-xlsx-exporter
        depends_on:
            - kafka
            - minio
            - vault
        ports:
            - 26300:26300
        environment:
            BIND_ADDR:          ":26300"
            KAFKA_ADDR:         "kafka:9092"
            DATASET_API_URL:    "http://dp-dataset-api:22000"
            #!!! get rid of cantabular server, etc
            CANTABULAR_URL:     "http://dp-cantabular-server:8491"
            SERVICE_AUTH_TOKEN: "testToken"
            COMPONENT_TEST_USE_LOG_FILE: "${COMPONENT_TEST_USE_LOG_FILE-false}"
            LOCAL_OBJECT_STORE:     "http://minio:9000"
            MINIO_ACCESS_KEY:       "minio-access-key"
            MINIO_SECRET_KEY:       "minio-secret-key"