version: '3.3'
services:
    dp-cantabular-xlsx-exporter:
        build:
            context: ../../../dp-cantabular-xlsx-exporter
            dockerfile: Dockerfile.local
        command:
            - go 
            - test 
            - -cover 
            - -race
            - -coverpkg=github.com/ONSdigital/dp-cantabular-xlsx-exporter/... 
            - -component
        volumes:
            - ../../:/dp-cantabular-xlsx-exporter
        depends_on:
            - kafka
            - minio
            - vault
        ports:
            - 26800:26800
        environment:
            BIND_ADDR:                          ":26800"
            SERVICE_AUTH_TOKEN:                 "testToken"
            COMPONENT_TEST_USE_LOG_FILE:        "${COMPONENT_TEST_USE_LOG_FILE-false}"
            LOCAL_OBJECT_STORE:                 "http://minio:9000"
            MINIO_ACCESS_KEY:                   "minio-access-key"
            MINIO_SECRET_KEY:                   "minio-secret-key"
            ENCRYPTION_DISABLED:                "true"
            STOP_CONSUMING_ON_UNHEALTHY:        "true"
            KAFKA_ADDR:                         "kafka:9092"
            KAFKA_CONSUMER_MIN_BROKERS_HEALTHY: 1
            KAFKA_PRODUCER_MIN_BROKERS_HEALTHY: 1
            KAFKA_SEC_PROTO:                    ""
