version: '3.3'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
      - MINIO_DEFAULT_BUCKETS=public-bucket,private-bucket
