version: '3.3'

services:
    vault:
      image: 'hashicorp/vault:latest'
      ports:
        - '8200:8200'
      entrypoint: vault server -dev -dev-kv-v1
      volumes:
        - ./vault/config:/vault/config
      environment:
        - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
        - VAULT_DEV_ROOT_TOKEN_ID=0000-0000-0000-0000
