// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-cantabular-xlsx-exporter/service"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"io"
	"sync"
)

// Ensure, that S3ClientMock does implement service.S3Client.
// If this is not the case, regenerate this file with moq.
var _ service.S3Client = &S3ClientMock{}

// S3ClientMock is a mock implementation of service.S3Client.
//
//	func TestSomethingThatUsesS3Client(t *testing.T) {
//
//		// make and configure a mocked service.S3Client
//		mockedS3Client := &S3ClientMock{
//			BucketNameFunc: func() string {
//				panic("mock out the BucketName method")
//			},
//			CheckerFunc: func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			ConfigFunc: func() aws.Config {
//				panic("mock out the Config method")
//			},
//			GetFunc: func(ctx context.Context, key string) (io.ReadCloser, *int64, error) {
//				panic("mock out the Get method")
//			},
//			GetWithPSKFunc: func(ctx context.Context, key string, psk []byte) (io.ReadCloser, *int64, error) {
//				panic("mock out the GetWithPSK method")
//			},
//			HeadFunc: func(ctx context.Context, key string) (*s3.HeadObjectOutput, error) {
//				panic("mock out the Head method")
//			},
//			UploadFunc: func(ctx context.Context, input *s3.PutObjectInput, options ...func(*manager.Uploader)) (*manager.UploadOutput, error) {
//				panic("mock out the Upload method")
//			},
//			UploadWithPSKFunc: func(ctx context.Context, input *s3.PutObjectInput, psk []byte) (*manager.UploadOutput, error) {
//				panic("mock out the UploadWithPSK method")
//			},
//		}
//
//		// use mockedS3Client in code that requires service.S3Client
//		// and then make assertions.
//
//	}
type S3ClientMock struct {
	// BucketNameFunc mocks the BucketName method.
	BucketNameFunc func() string

	// CheckerFunc mocks the Checker method.
	CheckerFunc func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error

	// ConfigFunc mocks the Config method.
	ConfigFunc func() aws.Config

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (io.ReadCloser, *int64, error)

	// GetWithPSKFunc mocks the GetWithPSK method.
	GetWithPSKFunc func(ctx context.Context, key string, psk []byte) (io.ReadCloser, *int64, error)

	// HeadFunc mocks the Head method.
	HeadFunc func(ctx context.Context, key string) (*s3.HeadObjectOutput, error)

	// UploadFunc mocks the Upload method.
	UploadFunc func(ctx context.Context, input *s3.PutObjectInput, options ...func(*manager.Uploader)) (*manager.UploadOutput, error)

	// UploadWithPSKFunc mocks the UploadWithPSK method.
	UploadWithPSKFunc func(ctx context.Context, input *s3.PutObjectInput, psk []byte) (*manager.UploadOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// BucketName holds details about calls to the BucketName method.
		BucketName []struct {
		}
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CheckState is the checkState argument value.
			CheckState *healthcheck.CheckState
		}
		// Config holds details about calls to the Config method.
		Config []struct {
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetWithPSK holds details about calls to the GetWithPSK method.
		GetWithPSK []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Psk is the psk argument value.
			Psk []byte
		}
		// Head holds details about calls to the Head method.
		Head []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Upload holds details about calls to the Upload method.
		Upload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *s3.PutObjectInput
			// Options is the options argument value.
			Options []func(*manager.Uploader)
		}
		// UploadWithPSK holds details about calls to the UploadWithPSK method.
		UploadWithPSK []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *s3.PutObjectInput
			// Psk is the psk argument value.
			Psk []byte
		}
	}
	lockBucketName    sync.RWMutex
	lockChecker       sync.RWMutex
	lockConfig        sync.RWMutex
	lockGet           sync.RWMutex
	lockGetWithPSK    sync.RWMutex
	lockHead          sync.RWMutex
	lockUpload        sync.RWMutex
	lockUploadWithPSK sync.RWMutex
}

// BucketName calls BucketNameFunc.
func (mock *S3ClientMock) BucketName() string {
	if mock.BucketNameFunc == nil {
		panic("S3ClientMock.BucketNameFunc: method is nil but S3Client.BucketName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBucketName.Lock()
	mock.calls.BucketName = append(mock.calls.BucketName, callInfo)
	mock.lockBucketName.Unlock()
	return mock.BucketNameFunc()
}

// BucketNameCalls gets all the calls that were made to BucketName.
// Check the length with:
//
//	len(mockedS3Client.BucketNameCalls())
func (mock *S3ClientMock) BucketNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBucketName.RLock()
	calls = mock.calls.BucketName
	mock.lockBucketName.RUnlock()
	return calls
}

// Checker calls CheckerFunc.
func (mock *S3ClientMock) Checker(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("S3ClientMock.CheckerFunc: method is nil but S3Client.Checker was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}{
		ContextMoqParam: contextMoqParam,
		CheckState:      checkState,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(contextMoqParam, checkState)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedS3Client.CheckerCalls())
func (mock *S3ClientMock) CheckerCalls() []struct {
	ContextMoqParam context.Context
	CheckState      *healthcheck.CheckState
} {
	var calls []struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Config calls ConfigFunc.
func (mock *S3ClientMock) Config() aws.Config {
	if mock.ConfigFunc == nil {
		panic("S3ClientMock.ConfigFunc: method is nil but S3Client.Config was just called")
	}
	callInfo := struct {
	}{}
	mock.lockConfig.Lock()
	mock.calls.Config = append(mock.calls.Config, callInfo)
	mock.lockConfig.Unlock()
	return mock.ConfigFunc()
}

// ConfigCalls gets all the calls that were made to Config.
// Check the length with:
//
//	len(mockedS3Client.ConfigCalls())
func (mock *S3ClientMock) ConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConfig.RLock()
	calls = mock.calls.Config
	mock.lockConfig.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *S3ClientMock) Get(ctx context.Context, key string) (io.ReadCloser, *int64, error) {
	if mock.GetFunc == nil {
		panic("S3ClientMock.GetFunc: method is nil but S3Client.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedS3Client.GetCalls())
func (mock *S3ClientMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetWithPSK calls GetWithPSKFunc.
func (mock *S3ClientMock) GetWithPSK(ctx context.Context, key string, psk []byte) (io.ReadCloser, *int64, error) {
	if mock.GetWithPSKFunc == nil {
		panic("S3ClientMock.GetWithPSKFunc: method is nil but S3Client.GetWithPSK was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		Psk []byte
	}{
		Ctx: ctx,
		Key: key,
		Psk: psk,
	}
	mock.lockGetWithPSK.Lock()
	mock.calls.GetWithPSK = append(mock.calls.GetWithPSK, callInfo)
	mock.lockGetWithPSK.Unlock()
	return mock.GetWithPSKFunc(ctx, key, psk)
}

// GetWithPSKCalls gets all the calls that were made to GetWithPSK.
// Check the length with:
//
//	len(mockedS3Client.GetWithPSKCalls())
func (mock *S3ClientMock) GetWithPSKCalls() []struct {
	Ctx context.Context
	Key string
	Psk []byte
} {
	var calls []struct {
		Ctx context.Context
		Key string
		Psk []byte
	}
	mock.lockGetWithPSK.RLock()
	calls = mock.calls.GetWithPSK
	mock.lockGetWithPSK.RUnlock()
	return calls
}

// Head calls HeadFunc.
func (mock *S3ClientMock) Head(ctx context.Context, key string) (*s3.HeadObjectOutput, error) {
	if mock.HeadFunc == nil {
		panic("S3ClientMock.HeadFunc: method is nil but S3Client.Head was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockHead.Lock()
	mock.calls.Head = append(mock.calls.Head, callInfo)
	mock.lockHead.Unlock()
	return mock.HeadFunc(ctx, key)
}

// HeadCalls gets all the calls that were made to Head.
// Check the length with:
//
//	len(mockedS3Client.HeadCalls())
func (mock *S3ClientMock) HeadCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockHead.RLock()
	calls = mock.calls.Head
	mock.lockHead.RUnlock()
	return calls
}

// Upload calls UploadFunc.
func (mock *S3ClientMock) Upload(ctx context.Context, input *s3.PutObjectInput, options ...func(*manager.Uploader)) (*manager.UploadOutput, error) {
	if mock.UploadFunc == nil {
		panic("S3ClientMock.UploadFunc: method is nil but S3Client.Upload was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Input   *s3.PutObjectInput
		Options []func(*manager.Uploader)
	}{
		Ctx:     ctx,
		Input:   input,
		Options: options,
	}
	mock.lockUpload.Lock()
	mock.calls.Upload = append(mock.calls.Upload, callInfo)
	mock.lockUpload.Unlock()
	return mock.UploadFunc(ctx, input, options...)
}

// UploadCalls gets all the calls that were made to Upload.
// Check the length with:
//
//	len(mockedS3Client.UploadCalls())
func (mock *S3ClientMock) UploadCalls() []struct {
	Ctx     context.Context
	Input   *s3.PutObjectInput
	Options []func(*manager.Uploader)
} {
	var calls []struct {
		Ctx     context.Context
		Input   *s3.PutObjectInput
		Options []func(*manager.Uploader)
	}
	mock.lockUpload.RLock()
	calls = mock.calls.Upload
	mock.lockUpload.RUnlock()
	return calls
}

// UploadWithPSK calls UploadWithPSKFunc.
func (mock *S3ClientMock) UploadWithPSK(ctx context.Context, input *s3.PutObjectInput, psk []byte) (*manager.UploadOutput, error) {
	if mock.UploadWithPSKFunc == nil {
		panic("S3ClientMock.UploadWithPSKFunc: method is nil but S3Client.UploadWithPSK was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *s3.PutObjectInput
		Psk   []byte
	}{
		Ctx:   ctx,
		Input: input,
		Psk:   psk,
	}
	mock.lockUploadWithPSK.Lock()
	mock.calls.UploadWithPSK = append(mock.calls.UploadWithPSK, callInfo)
	mock.lockUploadWithPSK.Unlock()
	return mock.UploadWithPSKFunc(ctx, input, psk)
}

// UploadWithPSKCalls gets all the calls that were made to UploadWithPSK.
// Check the length with:
//
//	len(mockedS3Client.UploadWithPSKCalls())
func (mock *S3ClientMock) UploadWithPSKCalls() []struct {
	Ctx   context.Context
	Input *s3.PutObjectInput
	Psk   []byte
} {
	var calls []struct {
		Ctx   context.Context
		Input *s3.PutObjectInput
		Psk   []byte
	}
	mock.lockUploadWithPSK.RLock()
	calls = mock.calls.UploadWithPSK
	mock.lockUploadWithPSK.RUnlock()
	return calls
}
