// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/cantabular"
	"github.com/ONSdigital/dp-cantabular-xlsx-exporter/handler"
	"sync"
)

// Ensure, that CantabularClientMock does implement handler.CantabularClient.
// If this is not the case, regenerate this file with moq.
var _ handler.CantabularClient = &CantabularClientMock{}

// CantabularClientMock is a mock implementation of handler.CantabularClient.
//
//	func TestSomethingThatUsesCantabularClient(t *testing.T) {
//
//		// make and configure a mocked handler.CantabularClient
//		mockedCantabularClient := &CantabularClientMock{
//			GetDimensionsByNameFunc: func(contextMoqParam context.Context, getDimensionsByNameRequest cantabular.GetDimensionsByNameRequest) (*cantabular.GetDimensionsResponse, error) {
//				panic("mock out the GetDimensionsByName method")
//			},
//		}
//
//		// use mockedCantabularClient in code that requires handler.CantabularClient
//		// and then make assertions.
//
//	}
type CantabularClientMock struct {
	// GetDimensionsByNameFunc mocks the GetDimensionsByName method.
	GetDimensionsByNameFunc func(contextMoqParam context.Context, getDimensionsByNameRequest cantabular.GetDimensionsByNameRequest) (*cantabular.GetDimensionsResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDimensionsByName holds details about calls to the GetDimensionsByName method.
		GetDimensionsByName []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetDimensionsByNameRequest is the getDimensionsByNameRequest argument value.
			GetDimensionsByNameRequest cantabular.GetDimensionsByNameRequest
		}
	}
	lockGetDimensionsByName sync.RWMutex
}

// GetDimensionsByName calls GetDimensionsByNameFunc.
func (mock *CantabularClientMock) GetDimensionsByName(contextMoqParam context.Context, getDimensionsByNameRequest cantabular.GetDimensionsByNameRequest) (*cantabular.GetDimensionsResponse, error) {
	if mock.GetDimensionsByNameFunc == nil {
		panic("CantabularClientMock.GetDimensionsByNameFunc: method is nil but CantabularClient.GetDimensionsByName was just called")
	}
	callInfo := struct {
		ContextMoqParam            context.Context
		GetDimensionsByNameRequest cantabular.GetDimensionsByNameRequest
	}{
		ContextMoqParam:            contextMoqParam,
		GetDimensionsByNameRequest: getDimensionsByNameRequest,
	}
	mock.lockGetDimensionsByName.Lock()
	mock.calls.GetDimensionsByName = append(mock.calls.GetDimensionsByName, callInfo)
	mock.lockGetDimensionsByName.Unlock()
	return mock.GetDimensionsByNameFunc(contextMoqParam, getDimensionsByNameRequest)
}

// GetDimensionsByNameCalls gets all the calls that were made to GetDimensionsByName.
// Check the length with:
//
//	len(mockedCantabularClient.GetDimensionsByNameCalls())
func (mock *CantabularClientMock) GetDimensionsByNameCalls() []struct {
	ContextMoqParam            context.Context
	GetDimensionsByNameRequest cantabular.GetDimensionsByNameRequest
} {
	var calls []struct {
		ContextMoqParam            context.Context
		GetDimensionsByNameRequest cantabular.GetDimensionsByNameRequest
	}
	mock.lockGetDimensionsByName.RLock()
	calls = mock.calls.GetDimensionsByName
	mock.lockGetDimensionsByName.RUnlock()
	return calls
}
