---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.2

inputs:
  - name: dp-cantabular-xlsx-exporter

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-cantabular-xlsx-exporter/ci/scripts/build.sh
